site_name: Immersion-Based Italian Learning
docs_dir: site-src

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
    - toc.follow
    - header.autohide
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search:
      lang:
        - en
        - it
  - glightbox

nav:
  - Home: index.md
  - Guide: guide.md
  - Setup: setup.md
  - Immersion: immersion.md
  - Mining: mining.md
  - Resources: resources.md
  - Recommendations: recommendations.md
  - Miscellaneous: miscellaneous.md
